blank_issues_enabled: false
contact_links:
  - name: 🐜 android-libraries Repo
    url: https://github.com/MuntashirAkon/android-libraries
    about: Please send requests for new trackers and libraries to this repository
  - name: 📗 App Manager Docs
    url: https://muntashirakon.github.io/AppManager/
    about: Please read documentation carefully before submitting an issue
